# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'qplayer2demo' do
  pod 'Bugly'
  pod 'Masonry', '1.0.1'
  #pod 'qplayer2-core'
end
